### PR TITLE
Get standalone docker image containing core demo programs.

### PR DESCRIPTION
**Pull request by mstemm**
Update the outrigger docker image to not explicitly install the
adapters or juttle any longer. This is no longer required with #51.

Add a new juttle program index.juttle that creates a table containing
markdown links to all the core-demo juttle programs.

Add a new docker image juttle/core-demo based on outrigger that also
copies in all the core-demo juttle programs. That way you can just
``run?path=/index.juttle`` and get links to all the programs (thanks
to Mike for the idea).

Add a build.sh script that handles the details of copying the juttle
scripts to a directory below the current directory (relative partent
directories aren't allowed in COPY commands) and running the docker
build command. By default the build.sh script uses the outrigger image
under the juttle/ organization (presumably the one available on docker
hub).

Modify the README.md to change the install instructions to refer to
the juttle/core-demo image and stop using ``outrigger-client
browser``.

@dmehra @demmer @rlgomes

### CODE REVIEW

**Comment by mstemm** [comment]
bump. I'd like to update the outrigger and core-demo images on docker hub soon so people can use it.

**Comment by dmehra** [comment]
+1 on this once README is expanded to say how to mount your juttles over the supplied juttles with -v, for those who want to edit the juttles.

**Comment by mstemm** [comment]
Made additional changes to:
  - have the root directory for outriggerd be /opt/outrigger/juttles
  - copy any examples in outrigger/examples to /opt/outrigger/examples within the image.
  - update readme.md to reflect these changes.

@demmer/@dmehra wanna take another look?

**Comment by demmer** [comment]
I think `examples/core` makes more sense than `examples/core-juttle` since everything is juttle... That said I don't feel strongly that we should block on that.

I also mentioned this before but it seems better to me that we would build the docker image out of the checked-out code and not out of the last push to npm, but I think I'm outvoted on that one.

Also you should squash before merge, but I'm ok to go ahead once that's done and we can revisit later.

**Comment by mstemm** [comment]
I don't believe the failure is related to any changes I made, so I'm going to merge and follow up on the failure.

**Pull request merged**
